# Generated by Django 4.2.7 on 2023-12-04 09:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_delete_moim"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Book",
        ),
    ]
